### ISSUE TITLE
UserAgreementPage Success

### ISSUE THREAD

**Issue by NGlasl** [sheadawson/silverstripe-useragreement#4]
The issue is the following line of code..

https://github.com/sheadawson/silverstripe-useragreement/blob/master/code/pages/UserAgreementPage.php#L155

When you're using **multisites** with say **site 1** and **site 2**, you may accept the user agreement on **site 2**, however be redirected to **site 1**.

My solution was to use `Director::absoluteBaseURL()` as opposed to `Director::baseURL()`. Though, I wasn't sure what to do in regards to `Security::default_login_dest()`. Using **swipestripe**, this is set to **/account** and takes you where a page may not exist on **site 2**.

Thoughts?

**Comment by sheadawson** [comment]
Not sure, whatever solution you find that works I'm happy to merge :)
